### ISSUE TITLE
Unable to add window android.view.ViewRootImpl -- specified display can not be found

### ISSUE THREAD

**Issue by tarasywe** [mybigday/react-native-external-display#583]
Hello
I am trying to run example from RNExternalDisplayExample packages but got next error

steps:
1) yarn in RNExternalDisplayExample folder
2) yarn android in RNExternalDisplayExample folder

<img width="1216" alt="Screenshot 2022-10-27 at 14 42 37" src="https://user-images.githubusercontent.com/6579553/198275406-37b1025e-ef7b-434c-8e33-1be426016e69.png">

meanwhile getScreens() function returns second display data

details from logcat

```
2022-10-27 16:31:45.430 14461-14485/com.rnexternaldisplayexample D/EGL_emulation: app_time_stats: avg=1117.44ms min=6.24ms max=8630.20ms count=10
2022-10-27 16:31:45.577 14461-14461/com.rnexternaldisplayexample E/unknown:ReactNative: Exception in native call
    android.view.WindowManager$InvalidDisplayException: Unable to add window android.view.ViewRootImpl$W@b7efa64 -- the specified display can not be found
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:1187)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:399)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:133)
        at android.app.Dialog.show(Dialog.java:345)
        at android.app.Presentation.show(Presentation.java:279)
        at com.externaldisplay.RNExternalDisplayView.updateScreen(RNExternalDisplayView.java:136)
        at com.externaldisplay.RNExternalDisplayView.addView(RNExternalDisplayView.java:44)
        at com.facebook.react.uimanager.ViewGroupManager.addView(ViewGroupManager.java:37)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:533)
        at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:217)
        at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:915)
        at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1026)
        at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1086)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1035)
        at android.view.Choreographer.doCallbacks(Choreographer.java:845)
        at android.view.Choreographer.doFrame(Choreographer.java:775)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
2022-10-27 16:31:45.581 14461-14461/com.rnexternaldisplayexample E/unknown:ReactNative: Exception in native call
    java.lang.IllegalStateException: View DecorView@8d8f182[] has already been added to the window manager.
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:371)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:133)
        at android.app.Dialog.show(Dialog.java:345)
        at android.app.Presentation.show(Presentation.java:279)
        at com.externaldisplay.RNExternalDisplayView.updateScreen(RNExternalDisplayView.java:136)
        at com.externaldisplay.RNExternalDisplayView.onHostResume(RNExternalDisplayView.java:101)
        at com.facebook.react.bridge.ReactContext$1.run(ReactContext.java:223)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```
Dispays information
```
[Display id 0: DisplayInfo{"Built-in Screen", displayId 0", displayGroupId 0, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS, FLAG_TRUSTED, real 1920 x 360, largest app 1920 x 1840, smallest app 360 x 280, appVsyncOff 1000000, presDeadline 16666666, mode 1, defaultMode 1, modes [{id=1, width=1920, height=360, fps=60.000004, alternativeRefreshRates=[]}], hdrCapabilities HdrCapabilities{mSupportedHdrTypes=[], mMaxLuminance=500.0, mMaxAverageLuminance=500.0, mMinLuminance=0.0}, userDisabledHdrTypes [], minimalPostProcessingSupported false, rotation 0, state ON}, DisplayMetrics{density=2.0, width=1920, height=328, scaledDensity=2.0, xdpi=320.0, ydpi=320.0}, isValid=true, Display id 2: DisplayInfo{"Emulator 2D Display", displayId 2", displayGroupId 0, FLAG_SHOULD_SHOW_SYSTEM_DECORATIONS, FLAG_TRUSTED, real 1920 x 1080, largest app 1920 x 1824, smallest app 1080 x 984, appVsyncOff 0, presDeadline 16666666, mode 2, defaultMode 2, modes [{id=2, width=1920, height=1080, fps=60.0, alternativeRefreshRates=[]}], hdrCapabilities null, userDisabledHdrTypes [], minimalPostProcessingSupported false, rotation 0, state ON}, DisplayMetrics{density=1.3312501, width=1920, height=984, scaledDensity=1.3312501, xdpi=213.0, ydpi=213.0}, isValid=true]
```
as far i understood display on emulator is not a PRESENTATION type, so it can't find device with such type.
More details here
https://issuetracker.google.com/issues/227218392

Not the question is - is there any way to add support emulator second screen for Presentation usage?
Thanks!

**Comment by tm-sanjay** [comment]
How did you solve this?

**Comment by Axenu** [comment]
Check this article for a workaround: https://innovorder.dev/multi-screen-management-within-android-56ef9052f066
